10.1.2
appoliana/SPBworks pull request #5
Opened 2018-02-16 06:03 UTC by appoliana

2018-02-17 07:38 UTC, yurii-litvinov requested changes

2018-02-17 07:38 UTC, yurii-litvinov commented on 1Semester/NewFolder/10.1/main.cpp
> +    }
Можно было проще:
```c++
for (int town : towns) {
    if (town == -1) {
         return true;
    }
}
```

2018-02-17 07:38 UTC, yurii-litvinov commented on 1Semester/NewFolder/10.1/main.cpp
> +    explicit Edge(int first, int second, int length)
А зачем здесь explicit? :)

2018-02-17 07:38 UTC, yurii-litvinov commented on 1Semester/NewFolder/10.1/main.cpp
> +    vector<vector<Edge> > edges(numberOfTowns);
А зачем пробел перед ">"? :)

2018-02-17 07:38 UTC, yurii-litvinov commented on 1Semester/NewFolder/10.1/main.cpp
> +        int length;
неинициализированные переменные

2018-02-17 07:38 UTC, yurii-litvinov commented on 1Semester/NewFolder/10.1/main.cpp
> +        towns[country] = static_cast<int>(i);
А зачем каст? :)

2018-02-17 07:38 UTC, yurii-litvinov commented on 1Semester/NewFolder/10.1/main.cpp
> +    return 0;
Вся содержательная часть в main-е, так нельзя

2018-02-17 15:14 UTC, appoliana commented on 1Semester/NewFolder/10.1/main.cpp
> +    explicit Edge(int first, int second, int length)
чтобы не было случайного приведения типов

2018-02-17 15:15 UTC, yurii-litvinov commented on 1Semester/NewFolder/10.1/main.cpp
> +    explicit Edge(int first, int second, int length)
А возможно ли здесь случайное приведение типов?

2018-02-24 11:25 UTC, yurii-litvinov requested changes

2018-02-24 11:25 UTC, yurii-litvinov commented on 1Semester/NewFolder/10.1/main.cpp
> +void searchOfTheAnswer(vector<int> &towns, vector<vector<Edge>> &edges, int numberOfCountries);
Не компилится, Edge объявлен под этой строчкой, следовательно, тут ещё не виден

2018-02-27 15:29 UTC, merged